{ pkgs, config, ... }:

let
  terminal = "${pkgs.ghostty}/bin/ghostty";

  # Walker application launcher for Wayland
  quick_menu = "${pkgs.walker}/bin/walker -m runner";
  full_menu = "${pkgs.walker}/bin/walker";
  file_menu = "${pkgs.walker}/bin/walker -m finder";
  window_menu = "${pkgs.walker}/bin/walker -m windows";

  # Power menu using wlogout
  powermenu = "${pkgs.wlogout}/bin/wlogout";
  # Screen locker
  lockscreen = "${pkgs.swaylock-effects}/bin/swaylock -f -c 000000 --clock --effect-blur 7x5";
  # Mail client
  mail = "mailspring --password-store='gnome-libsecret'";

  # Screenshot tools (Wayland-native)
  screenshot_select = "${pkgs.grimblast}/bin/grimblast --notify copy area";
  screenshot_full = "${pkgs.grimblast}/bin/grimblast --notify copy screen";

  # Day/night screen adjustment
  daynightscreen = "${pkgs.wlsunset}/bin/wlsunset -l 43.841667 -L 10.502778";

  # Stylix colors (hex without # prefix)
  colors = config.lib.stylix.colors;

  # Helper: convert stylix hex color (e.g. "1e1e2e") to MangoWC RGBA format (e.g. "0x1e1e2eff")
  toMangoColor = hex: "0x${hex}ff";
  toMangoColorAlpha = hex: alpha: "0x${hex}${alpha}";
in
{
  home = {
    packages = with pkgs; [
      # Wayland essentials for MangoWC
      adwaita-icon-theme
      adwaita-qt
      adwaita-qt6
      bemenu
      clipman
      dconf
      dracula-theme
      eww
      fuseiso
      fuzzel
      gammastep
      geoclue2
      ghostty
      glpaper
      gnome-themes-extra
      grim
      grimblast
      gsettings-desktop-schemas
      kitty
      lavalauncher
      libva-utils
      mako
      pinentry-bemenu
      polkit_gnome
      qt5.qtwayland
      qt6.qmake
      qt6.qtwayland
      shotman
      slurp
      swaybg
      swaylock-effects
      swww
      tofi
      udiskie
      wayland
      wbg
      wdisplays
      wev
      wl-clipboard
      wl-gammactl
      wl-screenrec
      wlogout
      wlr-randr
      wlroots
      wlsunset
      wshowkeys
      wtype
      xdg-desktop-portal
      xdg-desktop-portal-gtk
      xdg-utils
      ydotool
    ];
  };

  # MangoWC config file (~/.config/mango/config.conf)
  home.file.".config/mango/config.conf" = {
    text = ''
      # MangoWC Configuration
      # Generated by NixOS Home Manager
      # dwm-style Wayland compositor with scenefx effects
      #
      # Docs: https://mangowc.vercel.app/docs

      # ===========================
      # Environment Variables
      # ===========================
      env=NIXOS_OZONE_WL,1
      env=MOZ_ENABLE_WAYLAND,1
      env=QT_QPA_PLATFORM,wayland
      env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
      env=GDK_BACKEND,wayland,x11
      env=XDG_CURRENT_DESKTOP,wlroots
      env=XDG_SESSION_TYPE,wayland
      env=XDG_SESSION_DESKTOP,mango
      env=ELECTRON_OZONE_PLATFORM_HINT,wayland
      env=SDL_VIDEODRIVER,wayland
      env=_JAVA_AWT_WM_NONREPARENTING,1
      env=XCURSOR_SIZE,24

      # ===========================
      # Autostart
      # ===========================
      exec-once=${pkgs.dbus}/bin/dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP NIXOS_OZONE_WL ELECTRON_OZONE_PLATFORM_HINT
      exec-once=${pkgs.waybar}/bin/waybar
      exec-once=${pkgs.mako}/bin/mako
      exec-once=${pkgs.variety}/bin/variety
      exec-once=${daynightscreen}
      exec-once=${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1
      exec-once=${pkgs.wl-clipboard}/bin/wl-paste --type text --watch ${pkgs.clipman}/bin/clipman store

      # ===========================
      # Appearance / Theming
      # ===========================
      # Border
      borderpx=2

      # Gaps (matching Hyprland: inner=5, outer=10)
      gappih=5
      gappiv=5
      gappoh=10
      gappov=10

      # Colors (Stylix-integrated)
      rootcolor=${toMangoColor colors.base00}
      bordercolor=${toMangoColor colors.base03}
      focuscolor=${toMangoColor colors.base0D}
      urgentcolor=${toMangoColor colors.base08}
      maximizescreencolor=${toMangoColor colors.base0B}
      scratchpadcolor=${toMangoColor colors.base0E}
      globalcolor=${toMangoColor colors.base0C}
      overlaycolor=${toMangoColor colors.base0A}

      # Cursor
      cursor_size=24

      # ===========================
      # Visual Effects (scenefx)
      # ===========================
      # Blur (matching Hyprland blur settings)
      blur=1
      blur_layer=1
      blur_optimized=1
      blur_params_radius=8
      blur_params_num_passes=3
      blur_params_noise=0.02
      blur_params_brightness=0.8
      blur_params_contrast=0.9
      blur_params_saturation=1.2

      # Shadows
      shadows=1
      layer_shadows=0
      shadow_only_floating=0
      shadows_size=12
      shadows_blur=15
      shadows_position_x=-5
      shadows_position_y=-5
      shadowscolor=${toMangoColorAlpha "000000" "80"}

      # Corner radius (matching Hyprland rounding = 10)
      border_radius=10
      no_radius_when_single=0

      # Opacity (matching Hyprland: active 0.95, inactive 0.85)
      focused_opacity=0.95
      unfocused_opacity=0.85

      # ===========================
      # Animations
      # ===========================
      animations=1
      layer_animations=1

      # Animation types
      animation_type_open=zoom
      animation_type_close=fade
      layer_animation_type_open=slide
      layer_animation_type_close=fade

      # Fade
      animation_fade_in=1
      animation_fade_out=1
      fadein_begin_opacity=0.3
      fadeout_begin_opacity=0.5

      # Zoom
      zoom_initial_ratio=0.3
      zoom_end_ratio=0.85

      # Durations (ms)
      animation_duration_move=400
      animation_duration_open=350
      animation_duration_tag=250
      animation_duration_close=250
      animation_duration_focus=0

      # Bezier curves (matching Hyprland fadeBezier: 0.1, 0.9, 0.1, 1)
      animation_curve_open=0.1,0.9,0.1,1
      animation_curve_move=0.1,0.9,0.1,1
      animation_curve_tag=0.1,0.9,0.1,1
      animation_curve_close=0.08,0.92,0,1
      animation_curve_focus=0.1,0.9,0.1,1
      animation_curve_opafadein=0.1,0.9,0.1,1
      animation_curve_opafadeout=0.5,0.5,0.5,0.5

      # Tag animation direction (horizontal)
      tag_animation_direction=1

      # ===========================
      # Layouts
      # ===========================
      # Default to tile, with scroller available
      circle_layout=tile,scroller,monocle,grid

      # Master-stack settings (matching i3/sway defaults)
      new_is_master=1
      default_mfact=0.55
      default_nmaster=1
      smartgaps=0

      # Scroller settings
      scroller_structs=20
      scroller_default_proportion=0.9
      scroller_focus_center=0
      scroller_prefer_center=0
      scroller_prefer_overspread=1
      scroller_proportion_preset=0.5,0.8,1.0
      scroller_ignore_proportion_single=1
      scroller_default_proportion_single=1.0

      # ===========================
      # Input
      # ===========================
      # Keyboard
      repeat_rate=25
      repeat_delay=600
      numlockon=0
      xkb_rules_layout=us
      xkb_rules_options=

      # Trackpad
      tap_to_click=1
      tap_and_drag=1
      trackpad_natural_scrolling=0
      scroll_method=1
      click_method=1
      drag_lock=1
      disable_while_typing=1
      left_handed=0

      # Mouse
      mouse_natural_scrolling=0
      accel_profile=2
      accel_speed=0.0

      # ===========================
      # Focus & Behavior
      # ===========================
      focus_on_activate=1
      sloppyfocus=1
      warpcursor=1
      cursor_hide_timeout=5
      focus_cross_monitor=1
      exchange_cross_monitor=1

      # ===========================
      # Overview Mode
      # ===========================
      enable_hotarea=1
      hotarea_size=10
      ov_tab_mode=0
      overviewgappi=5
      overviewgappo=30

      # ===========================
      # Scratchpad
      # ===========================
      scratchpad_width_ratio=0.8
      scratchpad_height_ratio=0.85

      # ===========================
      # System
      # ===========================
      xwayland_persistence=1
      adaptive_sync=0
      allow_shortcuts_inhibit=1
      allow_tearing=0

      # ===========================
      # Tag Rules (per-tag layouts)
      # ===========================
      # Tag 1: default tile layout
      tagrule=id:1,layout_name:tile,nmaster:1,mfact:0.55
      # Tag 2: scroller for browsing
      tagrule=id:2,layout_name:tile
      # Tag 3: monocle for focused work
      tagrule=id:3,layout_name:tile
      # Tag 9: communication (Discord/Slack)
      tagrule=id:9,layout_name:tile

      # ===========================
      # Window Rules
      # ===========================
      # Floating windows (matching sway/hyprland rules)
      windowrule=isfloating:1,appid:pavucontrol
      windowrule=isfloating:1,appid:nm-connection-editor
      windowrule=isfloating:1,appid:org.gnome.Calculator
      windowrule=isfloating:1,width:900,height:600,appid:org.gnome.Nautilus
      windowrule=isfloating:1,appid:org.gnome.Settings
      windowrule=isfloating:1,title:Picture-in-Picture
      windowrule=isfloating:1,appid:screenkey
      windowrule=isnoborder:1,appid:screenkey
      windowrule=isfloating:1,appid:blueman-manager
      windowrule=isfloating:1,appid:thunar
      windowrule=isfloating:1,width:1000,height:700,appid:pcmanfm

      # Terminal swallowing (MangoWC built-in feature)
      windowrule=isterm:1,appid:ghostty
      windowrule=isterm:1,appid:kitty
      windowrule=isterm:1,appid:Alacritty
      windowrule=isterm:1,appid:foot

      # Don't swallow these apps
      windowrule=noswallow:1,appid:firefox
      windowrule=noswallow:1,appid:brave-browser
      windowrule=noswallow:1,appid:chromium-browser

      # Force opacity on certain apps
      windowrule=focused_opacity:1.0,appid:firefox
      windowrule=focused_opacity:1.0,appid:brave-browser
      windowrule=focused_opacity:1.0,appid:chromium-browser
      windowrule=focused_opacity:1.0,appid:mpv
      windowrule=focused_opacity:1.0,appid:vlc

      # Named scratchpad for terminal
      windowrule=isnamedscratchpad:1,width:1280,height:800,appid:ghostty-scratch

      # ===========================
      # Layer Rules
      # ===========================
      layerrule=layer_name:walker,animation_type_open:zoom,animation_type_close:fade
      layerrule=layer_name:waybar,noanim:1
      layerrule=layer_name:notifications,noblur:1

      # ===========================
      # Key Modes
      # ===========================
      keymode=common
      # Config reload available in all modes
      bind=SUPER,r,reload_config,

      keymode=default

      # ===========================
      # Key Bindings
      # ===========================

      # --- Applications ---
      bind=SUPER,Return,spawn,${terminal}
      bind=SUPER,d,spawn,${full_menu}
      bind=SUPER+SHIFT,d,spawn,${quick_menu}
      bind=SUPER+SHIFT,e,spawn,${file_menu}
      bind=SUPER+SHIFT,w,spawn,${window_menu}
      bind=SUPER+SHIFT,m,spawn,${mail}

      # --- System Controls ---
      bind=SUPER+CTRL,q,spawn,${lockscreen}
      bind=SUPER+CTRL+SHIFT,q,spawn,${powermenu}
      bind=SUPER+SHIFT+CTRL,r,reload_config,

      # --- Screenshots ---
      bind=SUPER+SHIFT,s,spawn,${screenshot_select}
      bind=SUPER+SHIFT,a,spawn,${screenshot_full}

      # --- Window Management ---
      bind=SUPER+SHIFT,c,killclient,
      bind=SUPER,f,togglefullscreen,
      bind=SUPER+SHIFT,space,togglefloating,
      bind=SUPER,space,togglemaximizescreen,0
      bind=SUPER+SHIFT,t,toggleglobal,
      bind=SUPER,minus,toggle_scratchpad,
      bind=SUPER+SHIFT,minus,spawn,${terminal} --class=ghostty-scratch

      # --- Focus (vim-style hjkl) ---
      bind=SUPER,h,focusdir,left
      bind=SUPER,j,focusstack,next
      bind=SUPER,k,focusstack,prev
      bind=SUPER,l,focusdir,right

      # Focus last window
      bind=SUPER,Tab,toggleoverview,1

      # --- Move / Swap Windows ---
      bind=SUPER+SHIFT,h,exchange_client,left
      bind=SUPER+SHIFT,j,exchange_stack_client,next
      bind=SUPER+SHIFT,k,exchange_stack_client,prev
      bind=SUPER+SHIFT,l,exchange_client,right
      bind=SUPER+SHIFT,Return,zoom,

      # --- Tags (workspaces) ---
      # View tag
      bind=SUPER,1,view,0
      bind=SUPER,2,view,1
      bind=SUPER,3,view,2
      bind=SUPER,4,view,3
      bind=SUPER,5,view,4
      bind=SUPER,6,view,5
      bind=SUPER,7,view,6
      bind=SUPER,8,view,7
      bind=SUPER,9,view,8

      # Move window to tag
      bind=SUPER+SHIFT,1,tag,0
      bind=SUPER+SHIFT,2,tag,1
      bind=SUPER+SHIFT,3,tag,2
      bind=SUPER+SHIFT,4,tag,3
      bind=SUPER+SHIFT,5,tag,4
      bind=SUPER+SHIFT,6,tag,5
      bind=SUPER+SHIFT,7,tag,6
      bind=SUPER+SHIFT,8,tag,7
      bind=SUPER+SHIFT,9,tag,8

      # Navigate tags left/right
      bind=SUPER+CTRL,h,viewtoleft_have_client,
      bind=SUPER+CTRL,l,viewtoright_have_client,

      # --- Layouts ---
      bind=SUPER,n,switch_layout,
      bind=SUPER,t,setlayout,tile
      bind=SUPER,s,setlayout,scroller
      bind=SUPER,w,setlayout,monocle
      bind=SUPER,g,setlayout,grid

      # Master/stack ratio
      bind=SUPER,bracketleft,setmfact,-0.05
      bind=SUPER,bracketright,setmfact,+0.05
      bind=SUPER,equal,incnmaster,1
      bind=SUPER+SHIFT,equal,incnmaster,-1

      # Gaps
      bind=SUPER+CTRL,bracketleft,incgaps,-1
      bind=SUPER+CTRL,bracketright,incgaps,+1
      bind=SUPER,0,togglegaps,

      # Scroller proportions
      bind=SUPER+SHIFT,bracketleft,set_proportion,-0.1
      bind=SUPER+SHIFT,bracketright,set_proportion,+0.1
      bind=SUPER+CTRL,p,switch_proportion_preset,

      # --- Monitor ---
      bind=SUPER,comma,focusmon,left
      bind=SUPER,period,focusmon,right
      bind=SUPER+SHIFT,comma,tagmon,left
      bind=SUPER+SHIFT,period,tagmon,right

      # --- Resize Mode ---
      keymode=resize
      bind=NONE,h,resizewin,-20,0
      bind=NONE,l,resizewin,20,0
      bind=NONE,k,resizewin,0,-20
      bind=NONE,j,resizewin,0,20
      bind=SHIFT,h,resizewin,-100,0
      bind=SHIFT,l,resizewin,100,0
      bind=SHIFT,k,resizewin,0,-100
      bind=SHIFT,j,resizewin,0,100
      bind=NONE,Escape,setkeymode,default
      bind=NONE,Return,setkeymode,default

      keymode=default
      bind=SUPER+ALT,r,setkeymode,resize

      # --- Resize (direct, matching hyprland) ---
      bind=SUPER+ALT,h,resizewin,-20,0
      bind=SUPER+ALT,l,resizewin,20,0
      bind=SUPER+ALT,k,resizewin,0,-20
      bind=SUPER+ALT,j,resizewin,0,20
      bind=SUPER+SHIFT+ALT,h,resizewin,-100,0
      bind=SUPER+SHIFT+ALT,l,resizewin,100,0
      bind=SUPER+SHIFT+ALT,k,resizewin,0,-100
      bind=SUPER+SHIFT+ALT,j,resizewin,0,100

      # --- Floating Window Movement ---
      bind=SUPER+CTRL+SHIFT,h,movewin,-50,0
      bind=SUPER+CTRL+SHIFT,l,movewin,50,0
      bind=SUPER+CTRL+SHIFT,k,movewin,0,-50
      bind=SUPER+CTRL+SHIFT,j,movewin,0,50

      # ===========================
      # Mouse Bindings
      # ===========================
      mousebind=SUPER,btn_left,moveresize,curmove
      mousebind=SUPER,btn_right,moveresize,curresize
      mousebind=SUPER,btn_middle,togglemaximizescreen,0

      # ===========================
      # Scroll (Axis) Bindings
      # ===========================
      axisbind=SUPER,UP,viewtoleft_have_client,
      axisbind=SUPER,DOWN,viewtoright_have_client,
      axisbind=ALT,UP,focusstack,prev
      axisbind=ALT,DOWN,focusstack,next

      # ===========================
      # Gesture Bindings (trackpad)
      # ===========================
      gesturebind=none,left,3,focusdir,left
      gesturebind=none,right,3,focusdir,right
      gesturebind=none,up,3,toggleoverview,1
      gesturebind=none,down,3,toggleoverview,1
      gesturebind=none,left,4,viewtoleft_have_client,
      gesturebind=none,right,4,viewtoright_have_client,

      # ===========================
      # Media Keys (locked = work even in lockscreen)
      # ===========================
      bindl=NONE,XF86AudioRaiseVolume,spawn,${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
      bindl=NONE,XF86AudioLowerVolume,spawn,${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
      bindl=NONE,XF86AudioMute,spawn,${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
      bindl=NONE,XF86MonBrightnessUp,spawn,${pkgs.brightnessctl}/bin/brightnessctl set +5%
      bindl=NONE,XF86MonBrightnessDown,spawn,${pkgs.brightnessctl}/bin/brightnessctl set 5%-
      bindl=NONE,XF86AudioPlay,spawn,${pkgs.playerctl}/bin/playerctl play-pause
      bindl=NONE,XF86AudioNext,spawn,${pkgs.playerctl}/bin/playerctl next
      bindl=NONE,XF86AudioPrev,spawn,${pkgs.playerctl}/bin/playerctl previous

      # ===========================
      # Lid Switch
      # ===========================
      switchbind=fold,spawn,${lockscreen}
    '';
  };

  # Systemd user service for MangoWC session environment
  systemd.user.services.mango-session-env = {
    Unit = {
      Description = "Set MangoWC session environment variables for Wayland";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session-pre.target" ];
    };

    Service = {
      Type = "oneshot";
      ExecStart = pkgs.writeShellScript "mango-env-setup" ''
        ${pkgs.systemd}/bin/systemctl --user import-environment \
          SSH_AUTH_SOCK \
          WAYLAND_DISPLAY \
          XDG_CURRENT_DESKTOP \
          XDG_SESSION_DESKTOP \
          XDG_SESSION_TYPE \
          NIXOS_OZONE_WL \
          ELECTRON_OZONE_PLATFORM_HINT \
          QT_QPA_PLATFORM \
          GDK_BACKEND \
          MOZ_ENABLE_WAYLAND

        ${pkgs.dbus}/bin/dbus-update-activation-environment --systemd \
          SSH_AUTH_SOCK \
          WAYLAND_DISPLAY \
          XDG_CURRENT_DESKTOP \
          XDG_SESSION_DESKTOP \
          XDG_SESSION_TYPE \
          NIXOS_OZONE_WL
      '';
      RemainAfterExit = true;
    };

    Install = {
      WantedBy = [ "graphical-session.target" ];
    };
  };
}
# vim: set ts=2 sw=2 et ai list nu
