{ config, pkgs, ... }:

let
  # Stylix colors for theming
  colors = config.lib.stylix.colors;
  fontName = config.stylix.fonts.monospace.name;
  fontSize = builtins.toString config.stylix.fonts.sizes.applications;
in
{
  # Walker config directory and files
  # This fixes: "Couldn't find config dir in either ~/.config/ or /etc/xdg/"
  home.file.".config/walker/config.toml" = {
    text = ''
      # Walker Application Launcher Configuration
      # Generated by NixOS Home Manager
      # Docs: https://walkerlauncher.com/

      # General settings
      force_keyboard_focus = true
      close_when_open = true
      click_to_close = true
      as_window = false
      single_click_activation = true
      selection_wrap = true
      global_argument_delimiter = "#"
      exact_search_prefix = "'"
      theme = "stylix"
      disable_mouse = false
      debug = false
      page_jump_items = 10
      hide_quick_activation = false
      hide_action_hints = false
      hide_action_hints_dmenu = true
      hide_return_action = false
      resume_last_query = false
      actions_as_menu = false
      autoplay_videos = false

      # Layer shell settings
      [shell]
      layer = "overlay"
      anchor_top = true
      anchor_bottom = true
      anchor_left = true
      anchor_right = true

      # Column widths
      [columns]
      "symbols" = 3

      # Placeholders
      [placeholders]

      [placeholders.default]
      input = "Search..."
      list = "No Results"

      [placeholders.runner]
      input = "Run command..."
      list = "No matching commands"

      [placeholders.finder]
      input = "Find files..."
      list = "No files found"

      [placeholders.windows]
      input = "Switch window..."
      list = "No open windows"

      [placeholders.clipboard]
      input = "Search clipboard..."
      list = "Clipboard empty"

      # Keybindings
      [keybinds]
      close = ["Escape"]
      next = ["Down", "ctrl j"]
      previous = ["Up", "ctrl k"]
      left = ["Left", "ctrl h"]
      right = ["Right", "ctrl l"]
      down = ["Down"]
      up = ["Up"]
      toggle_exact = ["ctrl e"]
      resume_last_query = ["ctrl r"]
      quick_activate = ["F1", "F2", "F3", "F4"]
      page_down = ["Page_Down", "ctrl d"]
      page_up = ["Page_Up", "ctrl u"]
      show_actions = ["alt j"]

      # Provider configuration
      [providers]
      default = ["desktopapplications", "calc", "websearch"]
      empty = ["desktopapplications"]
      ignore_preview = []
      max_results = 50

      # Provider prefix mappings
      [[providers.prefixes]]
      prefix = ";"
      provider = "providerlist"

      [[providers.prefixes]]
      prefix = ">"
      provider = "runner"

      [[providers.prefixes]]
      prefix = "/"
      provider = "files"

      [[providers.prefixes]]
      prefix = "."
      provider = "symbols"

      [[providers.prefixes]]
      prefix = "="
      provider = "calc"

      [[providers.prefixes]]
      prefix = "@"
      provider = "websearch"

      [[providers.prefixes]]
      prefix = ":"
      provider = "clipboard"

      [[providers.prefixes]]
      prefix = "$"
      provider = "windows"

      [[providers.prefixes]]
      prefix = "%"
      provider = "bookmarks"

      # Provider actions
      [providers.actions]

      desktopapplications = [
        { action = "start", default = true, bind = "Return" },
        { action = "start:keep", label = "open+next", bind = "shift Return", after = "KeepOpen" },
        { action = "new_instance", label = "new instance", bind = "ctrl Return" },
        { action = "pin", bind = "ctrl p", after = "AsyncReload" },
        { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
      ]

      runner = [
        { action = "run", default = true, bind = "Return" },
        { action = "run:terminal", label = "in terminal", bind = "ctrl Return" },
      ]

      websearch = [
        { action = "search", default = true, bind = "Return" },
      ]

      calc = [
        { action = "copy", default = true, bind = "Return" },
        { action = "delete", bind = "ctrl d", after = "AsyncReload" },
        { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
      ]

      files = [
        { action = "open", default = true, bind = "Return" },
        { action = "opendir", label = "open dir", bind = "ctrl Return" },
        { action = "copypath", label = "copy path", bind = "ctrl shift c" },
        { action = "copyfile", label = "copy file", bind = "ctrl c" },
      ]

      clipboard = [
        { action = "copy", default = true, bind = "Return" },
        { action = "remove", bind = "ctrl d", after = "AsyncClearReload" },
        { action = "remove_all", label = "clear", bind = "ctrl shift d", after = "AsyncClearReload" },
        { action = "show_images_only", label = "only images", bind = "ctrl i", after = "AsyncClearReload" },
        { action = "show_text_only", label = "only text", bind = "ctrl i", after = "AsyncClearReload" },
        { action = "pin", bind = "ctrl p", after = "AsyncClearReload" },
      ]

      windows = [
        { action = "focus", default = true, bind = "Return" },
        { action = "close", bind = "ctrl d" },
      ]

      bookmarks = [
        { action = "open", default = true, bind = "Return" },
        { action = "copyurl", label = "copy url", bind = "ctrl c" },
      ]

      symbols = [
        { action = "copy", default = true, bind = "Return" },
      ]

      dmenu = [
        { action = "select", default = true, bind = "Return" },
      ]
    '';
  };

  # Walker theme (Stylix-integrated)
  home.file.".config/walker/themes/stylix/style.css" = {
    text = ''
      /* Walker Theme - Stylix Integrated */
      /* Generated by NixOS Home Manager */

      /* Color definitions from Stylix */
      @define-color window_bg_color rgba(${
        let
          hex = colors.base00;
          r = builtins.substring 0 2 hex;
          g = builtins.substring 2 2 hex;
          b = builtins.substring 4 2 hex;
          hexToInt = h:
            let
              chars = {
                "0" = 0; "1" = 1; "2" = 2; "3" = 3; "4" = 4;
                "5" = 5; "6" = 6; "7" = 7; "8" = 8; "9" = 9;
                "a" = 10; "b" = 11; "c" = 12; "d" = 13; "e" = 14; "f" = 15;
                "A" = 10; "B" = 11; "C" = 12; "D" = 13; "E" = 14; "F" = 15;
              };
              h0 = builtins.substring 0 1 h;
              h1 = builtins.substring 1 1 h;
            in
              chars.${h0} * 16 + chars.${h1};
        in
          "${builtins.toString (hexToInt r)}, ${builtins.toString (hexToInt g)}, ${builtins.toString (hexToInt b)}"
      }, 0.92);
      @define-color accent_bg_color #${colors.base02};
      @define-color accent_color #${colors.base0D};
      @define-color theme_fg_color #${colors.base05};
      @define-color theme_fg_dimmed #${colors.base04};
      @define-color theme_selected_bg #${colors.base0D};
      @define-color theme_selected_fg #${colors.base00};
      @define-color theme_hover_bg #${colors.base01};
      @define-color theme_border_color #${colors.base03};
      @define-color error_bg_color #${colors.base08};
      @define-color error_fg_color #${colors.base05};
      @define-color success_color #${colors.base0B};
      @define-color warning_color #${colors.base0A};

      /* Main wrapper */
      .box-wrapper {
          background-color: @window_bg_color;
          border-radius: 16px;
          border: 2px solid @theme_border_color;
          padding: 16px;
          box-shadow: 0px 8px 24px rgba(0, 0, 0, 0.4);
          margin: 200px 25% 200px 25%;
          min-width: 500px;
      }

      /* Search input */
      .input {
          background-color: @accent_bg_color;
          color: @theme_fg_color;
          border: 1px solid @theme_border_color;
          border-radius: 12px;
          padding: 14px 18px;
          font-family: "${fontName}";
          font-size: ${fontSize}pt;
          caret-color: @accent_color;
          margin-bottom: 12px;
          min-height: 24px;
      }

      .input:focus {
          border-color: @accent_color;
          box-shadow: 0 0 0 1px @accent_color;
      }

      /* Placeholder text */
      .input placeholder {
          color: @theme_fg_dimmed;
          font-style: italic;
      }

      /* Results list */
      .list {
          background-color: transparent;
          border-radius: 8px;
      }

      /* Individual result items */
      .list-item {
          padding: 10px 14px;
          margin: 2px 0;
          border-radius: 8px;
          color: @theme_fg_color;
          transition: all 200ms ease;
      }

      .list-item:hover {
          background-color: @theme_hover_bg;
      }

      .list-item:selected {
          background-color: @theme_selected_bg;
          color: @theme_selected_fg;
      }

      .list-item:selected .icon {
          color: @theme_selected_fg;
      }

      .list-item:selected .description {
          color: @theme_selected_fg;
          opacity: 0.8;
      }

      /* Item text */
      .list-item .text {
          font-family: "${fontName}";
          font-size: ${fontSize}pt;
      }

      .list-item .description {
          font-size: ${builtins.toString (builtins.sub config.stylix.fonts.sizes.applications 1)}pt;
          color: @theme_fg_dimmed;
      }

      /* Icons */
      .icon {
          min-width: 24px;
          min-height: 24px;
          margin-right: 12px;
          color: @theme_fg_color;
      }

      .icon-large {
          min-width: 36px;
          min-height: 36px;
      }

      /* Preview pane */
      .preview {
          background-color: @accent_bg_color;
          border-radius: 8px;
          padding: 12px;
          margin-left: 12px;
          border: 1px solid @theme_border_color;
      }

      .preview .icon {
          min-width: 64px;
          min-height: 64px;
      }

      /* Calculator result */
      .calc-text {
          font-size: 20pt;
          font-weight: bold;
          color: @success_color;
          font-family: "${fontName}";
      }

      /* Keybinding labels */
      .keybind-label {
          background-color: @accent_bg_color;
          color: @theme_fg_dimmed;
          border-radius: 4px;
          padding: 2px 6px;
          font-size: ${builtins.toString (builtins.sub config.stylix.fonts.sizes.applications 2)}pt;
          font-family: "${fontName}";
          border: 1px solid @theme_border_color;
      }

      /* Quick activation buttons */
      .quick-activation {
          background-color: @accent_bg_color;
          color: @accent_color;
          border-radius: 4px;
          padding: 2px 8px;
          font-size: ${builtins.toString (builtins.sub config.stylix.fonts.sizes.applications 2)}pt;
          font-weight: bold;
          border: 1px solid @theme_border_color;
      }

      /* Error messages */
      .error {
          background-color: @error_bg_color;
          color: @error_fg_color;
          padding: 8px 12px;
          border-radius: 8px;
      }

      /* Scrollbar */
      scrollbar {
          background-color: transparent;
      }

      scrollbar slider {
          background-color: @theme_border_color;
          border-radius: 4px;
          min-width: 4px;
      }

      scrollbar slider:hover {
          background-color: @accent_color;
      }

      /* Action hints */
      .action-hint {
          color: @theme_fg_dimmed;
          font-size: ${builtins.toString (builtins.sub config.stylix.fonts.sizes.applications 2)}pt;
      }

      /* Provider labels */
      .provider-label {
          color: @accent_color;
          font-weight: bold;
          font-size: ${builtins.toString (builtins.sub config.stylix.fonts.sizes.applications 1)}pt;
          padding: 4px 8px;
      }

      /* Clipboard image preview */
      .clipboard-image {
          border-radius: 8px;
          border: 1px solid @theme_border_color;
      }

      /* Pin indicator */
      .pinned {
          color: @warning_color;
      }
    '';
  };
}
# vim: set ts=2 sw=2 et ai list nu
